export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SET_LOADING = 'SET_LOADING';
export const SET_CHECKED = 'SET_CHECKED';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const SET_SHOW_SWITCH = 'SET_SHOW_SWITCH';